### ISSUE TITLE
memory leak on gpu

### ISSUE THREAD

**Issue by khs8727** [dr-pato/audio_visual_speech_enhancement#15]
Hi, I got an memory issue(on RAM not VRAM) when running this code on gpu.
After training 1-2 epochs  (15000 test cases with 128 batchs), it was killed either with segmentation fault error or no error message.

I checked that meric process (SNR SDR stuff) makes growing up cpu utilization and RAM so I removed those, but the memory leak still doesn't disappered.

Any clues why the memory leak happends?

ubuntu 16.04 / tensorflow(gpu) 1.14 (also checked with 1.15) / GTX 1080 Ti

**Comment by dr-pato** [comment]
Hi @khs8727,
a batch size of 128 samples is very large for the models, you don't need to keep it so large. I used 8 batch size at most. So try to decrease it..
Maybe the memory leak due to computational graph growth. If you are able to find it, let me know. Sorry I have no time to check the code now in a short time.

**Comment by khs8727** [comment]
Hi @dr-pato 
I checked that TFRecords module grap system memory while loading data on VRAM and does not release properly. I am newbie in tensorflow, so couldn't figure out which point is actual problem.
Instead, I removed all TFRecords part and fed .npy files directly into tensorflow data pipeline. (saving all data in npy instead of TFRecords) 
Still RAM little growing up while training but RAM usage is much lower and no problem with training.
Thanks for your tip!!
