### ISSUE TITLE
little more detail about how to train AV c-ref model

### ISSUE THREAD

**Issue by khs8727** [dr-pato/audio_visual_speech_enhancement#16]
How I have a question reagarding training AV c-ref model.

1. what -mt options does for training? should it be 0 (other than -1) on vl2m model?
training_parser.add_argument('-mt', '--mask_threshold', type=float, default=-1,
                                 help='Threshold on estimated TBM for reconstruction ("vl2m" model only). If -1 (default) thresholding is not applied')

2. how many epoch did you trained for vl2m?
since metrics(SNR SDR stuff) of vl2m doesn't grow up fastly comparing to other models,
I don't know whether it train well during training, and how many epoch should I run.

below is your comments in other issue
```
---------------------------------------------------------------------------------------------------
If you want to train the AV c-ref you have to do the following steps (described in the paper in section 3.2):

Train the "vl2m" model (adam optimizer with 10^-4 as initial learning rate).
Save estimated TBMs of training, validation and test set with "testing" subcommand.
Train "av_concat_mask_ref" with oracle TBMs (adam optimizer with 10^-3 as initial learning rate).
Generate TFRecords using the estimated TBMs instead of oracle TBMs.
Select the best epoch of trained "av_concat_mask_ref" model and fine-tune the model with TFRecords of point 4.
Let me know if you are able to do all steps correctly.
---------------------------------------------------------------------------------------------------
```

**Comment by dr-pato** [comment]
Hi @khs8727,

> 1. what -mt options does for training? should it be 0 (other than -1) on vl2m model?
training_parser.add_argument('-mt', '--mask_threshold', type=float, default=-1,
help='Threshold on estimated TBM for reconstruction ("vl2m" model only). If -1 (default) thresholding is not applied')

the target of vl2m model is a binary mask, but the output is a value in range [0,1]. So if you want a binary mask in output you should apply a threshold. In my experiments I left the default value - no threshold applied, but you can change it to control the strength of the mask. Values near 1 discard more much tf bins while values near 0 are more relaxed. When you use vl2m together with AV c-ref model it is better to apply no threshold to avoid loss of information.

>2.  how many epoch did you trained for vl2m?
since metrics(SNR SDR stuff) of vl2m doesn't grow up fastly comparing to other models,
I don't know whether it train well during training, and how many epoch should I run.

The models I trained usually reached the best epoch after about 10 epochs. v2lm performs much worse compared to other models (see the paper) and the training is slower. Compare your results with the ones in the tables. You should obtain similar ones.

Hope this helps.

**Comment by khs8727** [comment]
I really appreciate for your kind reply!
